import type { Metadata } from "next";
import { Inter as Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import ViewCanvas from "@/components/ViewCanvas";

const inter = Inter<"--font-inter">({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "700", "800", "900"],
  style: "normal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} antialiased`}>
      <body className="overflow-x-hidden bg-yellow-300 font-inter">
        <Header />
        <main>{children}</main>
        <ViewCanvas />
      </body>
    </html>
  );
}
